# fly.toml app configuration file generated for 0-smoke-test on 2024-08-18T01:01:07-02:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '0-smoke-test'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 4040
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 4040
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 4040

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
